const STUDENTI = [

    ["27", "Edoardo", "Schenone", "0"],
    ["9", "Francesco", "Bechini", "1"],
    ["6", "Fabio", "Larosa", "2"],
    ["2", "Jacopo", "Luoni", "3"],
    ["24", "Francesco", "Della Corte", "4"],
    ["28", "Matias", "Motal", "5"],
    ["29", "Gael", "Daniel", "6"],
    ["16", "manuel", "hozu", "7"],
    ["11", "Alessandro", "Pallaro", "8"],
    ["17", "Cinzia", "Perona", "9"],
    ["12", "Pierre", "Fiorentino", "10"],
    ["1", "marco", "pacchiotti", "11"],
    ["26", "Leonardo", "Scardoni", "12"],
    ["25", "Gabriel", "Semeniuc", "13"],
    ["20", "Armir", "Trupja", "14"],
    ["10", "Federico", "Ruppa", "15"],
    ["19", "Biagina Antonella", "Alberti", "16"],
    ["23", "Luca", "Lopetti", "17"],
    ["15", "Daniele", "Busconi", "18"],
    ["18", "Andrea", "Ricci", "20"],
    ["5", "Lucas", "Giavelli", "22"],
    ["13", "Valentino", "Chatrian", "23"],
    ["7", "Giorgio", "Magliocca", "24"],
    ["22", "Andrea", "Azzalin ", "25"],
    ["14", "Giorgio ", "Modeo", "28"],
    ["8", "Edoardo", "Caon", "29"],
    ["4", "roberto", "bruno", "30"],
    ["3", "Paolo", "De Andreis", "30"],
    ["21", "Mattia", "Pacioni", "30"],

]
